import {CallHandler, ExecutionContext, Injectable, NestInterceptor,} from '@nestjs/common';
import {Reflector} from '@nestjs/core';
import {Observable, of} from 'rxjs';
import {MOCK_ROUTE_KEY} from '../constants/constants';
import {MockRouteOptions} from '../options/mockRoute.options';
import {MockFactory} from '../factories/mock.factory';

/**
 * Interceptor responsible for generating mock responses for routes
 * decorated with `@MockRoute`.
 *
 * `MockRouteInterceptor` checks metadata stored under `MOCK_ROUTE_KEY`
 * at both the handler and controller level. If metadata is present,
 * the interceptor bypasses the actual route handler and returns
 * a mock response generated by {@link MockFactory}.
 *
 * ## How it works
 * - When a route is decorated with `@MockRoute`, mock configuration
 *   (entity class, array mode, array length) is stored via metadata.
 * - At request time, the interceptor:
 *   1. Reads metadata using Nest's `Reflector`
 *   2. Decides whether to return mock data or continue to the handler
 *   3. Uses `MockFactory` to generate the mock value
 *   4. Wraps the mock object in an RxJS `Observable` and returns it
 *
 * The underlying controller method is *never executed* when mocks are enabled.
 *
 * ## Example
 * ```ts
 * @Get()
 * @MockRoute(ChatMock, { isArray: true, arrayLength: [3, 5] })
 * getChats() {
 *   // This will NOT run when the interceptor generates mock data
 * }
 * ```
 *
 * ## Mock resolution order
 * 1. Handler-level metadata (method)
 * 2. Controller-level metadata (class)
 *
 * This allows setting `@MockRoute` either globally for all controller methods
 * or individually for specific endpoints.
 *
 * ## When does the interceptor not run?
 * - If no metadata is found under `MOCK_ROUTE_KEY`
 * - If `MockRoute` is not applied to the route or controller
 *
 * In these cases, the request flows normally to the real handler.
 */
@Injectable()
export class MockRouteInterceptor implements NestInterceptor {
    constructor(
        private readonly reflector: Reflector,
        private readonly mockFactory: MockFactory,
    ) {
    }

    /**
     * Intercepts incoming HTTP requests and optionally replaces the response
     * with mock data if mock metadata is present.
     *
     * @param context NestJS execution context for the current request.
     * @param next Control flow to the next handler in the pipeline.
     * @returns An observable either containing mock data or the real handler output.
     */
    intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
        const handler = context.getHandler();
        const ctrl = context.getClass();

        const options =
            this.reflector.get<MockRouteOptions>(MOCK_ROUTE_KEY, handler) ??
            this.reflector.get<MockRouteOptions>(MOCK_ROUTE_KEY, ctrl);

        if (!options) {
            return next.handle();
        }

        const {entity, isArray, arrayLength} = options;

        if (isArray) {
            const [min = 1, max = 5] = arrayLength || [1, 5];
            const count = this.randomInt(min, max);
            const mock = this.mockFactory.createMany(entity as any, count);
            return of(mock);
        }

        const mock = this.mockFactory.create(entity as any);
        return of(mock);
    }

    /**
     * Returns a random integer between `min` and `max` (inclusive).
     *
     * Used to determine the size of mock arrays when `arrayLength` is configured.
     *
     * @internal
     */
    private randomInt(min: number, max: number): number {
        const from = Math.ceil(min);
        const to = Math.floor(max);
        return Math.floor(Math.random() * (to - from + 1)) + from;
    }
}